name: Version bump

on:
  workflow_dispatch:
jobs:
  bump-check:
    runs-on: ubuntu-latest
    steps:
      - name: "init"
        uses: gopidesupavan/first/init@init/v1.0.0
      - name: "run"
        uses: gopidesupavan/first/run@run/v1.0.0
