name: Version bump

on:
  workflow_dispatch:
jobs:
  bump-check:
    runs-on: ubuntu-latest
    steps:
      - name: "init"
        uses: gopidesupavan/monorepo-actions/first/init@init/v1.0.0
      - name: "run"
        uses: gopidesupavan/monorepo-actions/first/run@run/v2.0.0
      - uses: actions/checkout@v1.0.0
      - name: "Same checkout 2"
      - uses: actions/checkout@v2.0.0
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: "check"
        uses: actions/checkout@master
