name: Version bump

on:
  workflow_dispatch:
jobs:
  bump-check:
    runs-on: ubuntu-latest
    steps:
      - name: "init"
        uses: gopidesupavan/monorepo-actions/first/init@init/v2.0.0
      - name: "run"
        uses: gopidesupavan/monorepo-actions/first/run@run/v2.0.0
